[tool.poetry]
name = "NeoVic2006_brain_games"
version = "0.5.0"
description = "Updated with Fermat algorithm"
authors = ["Sergey Vengilevskiy <NeoVic2006@gmail.com>"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "^3.8"
prompt = "^0.4.1"


[tool.poetry.dev-dependencies]  
flake8 = "^3.8.3"


[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
brain-calc = "brain_games.scripts.brain-calc:main"
brain-prog = "brain_games.scripts.brain_prog:main"
brain-nod = "brain_games.scripts.brain_nod:main"
brain-fermat = "brain_games.scripts.brain_fermat:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

