[tool.poetry]
name = "NeoVic2006_brain_games"
version = "0.1.0"
description = ""
authors = ["Sergey Vengilevskiy <NeoVic2006@gmail.com>"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
brain-games = "brain_games.scripts.brain_games:main"   

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
